modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"

[[mods]]
modId = "cleardespawn"
version = "${file.jarVersion}"
displayName = "ClearDespawn"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile = "icon.png"
credits = "Thanks for IllusiveC4 for initially making the mod."
authors = "StrikerRocker"
description = '''
Flashes the item on ground after a certain amount of time to indicate its going to despawn
'''
[[dependencies.cleardespawn]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.cleardespawn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
