name: "Build Release"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-release:
    uses: StrikerRockers-Mods/.github/.github/workflows/build-release-v2.yml@main
    secrets: inherit
    with:
      forge-cf-id: 308656
      fabric-cf-id: 308793
      modrinth-id: yoJJjRRE
      fabric-dependencies: |
        fabric-api | depends | *
        cloth-config | depends | *
        modmenu | recommends | *